def note_helper(note) -> dict:
    return {
        "id": str(note["_id"]),
        "title": note["title"],
        "description": note.get("description"),
        "dept": note["dept"],
        "semester": note["semester"],
        "subject": note["subject"],
        "unit": note.get("unit"),
        "tags": note.get("tags", []),
        "exam_tag": note.get("exam_tag"),
        "note_type": note["note_type"],
        "file_url": note.get("file_url"),
        "external_link": note.get("external_link"),
        "status": note.get("status", "pending"),
        "uploader_id": str(note["uploader_id"]),
        "is_paid": note.get("is_paid", False),
        "price": note.get("price", 0),
        "views": note.get("views", 0),
        "downloads": note.get("downloads", 0),
        "ai": note.get("ai"),
        "avg_rating": note.get("avg_rating", 0),
        "review_count": note.get("review_count", 0),
        # Trust fields (populated by aggregation)
        "uploader_name": note.get("uploader_name"),
        "verified_seller": note.get("verified_seller", False),
        "college_name": note.get("college_name"),
        "seller_trust_level": note.get("seller_trust_level", "new"),
        "seller_total_sales": note.get("seller_total_sales", 0),
        "has_access": note.get("has_access", False),
    }
