export const ENDPOINTS = Object.freeze({
  notes: {
    list: "/notes",
    mine: "/notes/my",
    myRejected: "/notes/my/rejected",
    myPending: "/notes/my/pending",
    details: (noteId) => `/notes/${noteId}/details`,
    trending: "/notes/trending",
    semanticSearch: "/notes/semantic-search",
    versions: (noteId) => `/notes/${noteId}/versions`,
    confidence: (noteId) => `/notes/${noteId}/confidence`,
    nearDuplicates: (noteId) => `/notes/${noteId}/near-duplicates`,
    smartStudyPack: (noteId) => `/notes/${noteId}/smart-study-pack`,
    annotations: (noteId) => `/notes/${noteId}/annotations`,
    collaborators: (noteId) => `/notes/${noteId}/collaborators`,
  },
  purchases: {
    buy: (noteId) => `/purchase/${noteId}`,
    mine: "/purchase/my",
    has: (noteId) => `/purchase/has/${noteId}`,
  },
  payments: {
    createOrder: "/payments/create-order",
    verify: "/payments/verify",
    mockCheckout: "/payments/mock-checkout",
  },
  bundles: {
    list: "/bundles",
    create: "/bundles",
  },
  library: {
    mine: "/library/my",
  },
  bookmarks: {
    mine: "/bookmarks/my",
    byNote: (noteId) => `/bookmarks/${noteId}`,
  },
  likes: {
    mine: "/likes/my",
    byNote: (noteId) => `/likes/${noteId}`,
  },
  reviews: {
    note: (noteId) => `/reviews/note/${noteId}`,
  },
  recommendations: {
    alsoBought: (noteId) => `/recommendations/also-bought/${noteId}`,
  },
  ai: {
    workerHealth: "/ai/worker/health",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    readAll: "/notifications/read-all",
    readOne: (notificationId) => `/notifications/${notificationId}/read`,
    stream: "/notifications/stream",
    preferences: "/notifications/preferences",
    digest: "/notifications/digest",
  },
  ops: {
    health: "/ops/health",
    runtime: "/ops/runtime",
  },
  requests: {
    list: "/requests",
    create: "/requests",
    close: (requestId) => `/requests/${requestId}/close`,
    vote: (requestId) => `/requests/${requestId}/vote`,
    pledge: (requestId) => `/requests/${requestId}/pledge`,
    bounty: (requestId) => `/requests/${requestId}/bounty`,
    heatmap: "/requests/insights/demand-heatmap",
  },
  spaces: {
    mine: "/spaces/my",
    create: "/spaces",
    detail: (spaceId) => `/spaces/${spaceId}`,
    update: (spaceId) => `/spaces/${spaceId}`,
    delete: (spaceId) => `/spaces/${spaceId}`,
    join: (inviteCode) => `/spaces/join/${inviteCode}`,
    leave: (spaceId) => `/spaces/${spaceId}/leave`,
    regenerateInvite: (spaceId) => `/spaces/${spaceId}/regenerate-invite`,
    members: (spaceId) => `/spaces/${spaceId}/members`,
    kickMember: (spaceId, userId) => `/spaces/${spaceId}/members/${userId}`,
    updateMemberRole: (spaceId, userId) => `/spaces/${spaceId}/members/${userId}/role`,
    transferOwnership: (spaceId, userId) => `/spaces/${spaceId}/transfer-ownership/${userId}`,
    announcements: (spaceId) => `/spaces/${spaceId}/announcements`,
    deleteAnnouncement: (spaceId, announcementId) => `/spaces/${spaceId}/announcements/${announcementId}`,
    notes: (spaceId) => `/spaces/${spaceId}/notes`,
    removeSharedNote: (spaceId, shareId) => `/spaces/${spaceId}/notes/${shareId}`,
  },
  monetization: {
    couponsCreate: "/monetization/coupons",
    couponsMine: "/monetization/coupons/my",
    couponsApply: "/monetization/coupons/apply",
    campaignsCreate: "/monetization/campaigns",
    campaignsMine: "/monetization/campaigns/my",
    payoutsMine: "/monetization/payouts/me",
    passesCreate: "/monetization/passes",
    passesMine: "/monetization/passes/my",
    passesAvailable: "/monetization/passes/available",
    passSubscribe: (passId) => `/monetization/passes/${passId}/subscribe`,
    passSubscriptionsMine: "/monetization/passes/subscriptions/me",
  },
  admin: {
    analyticsFunnel: "/admin/analytics/funnel",
    domainCandidates: "/admin/domain-candidates",
    approveDomainCandidate: (domain) => `/admin/domain-candidates/${encodeURIComponent(domain)}/approve`,
    rejectDomainCandidate: (domain) => `/admin/domain-candidates/${encodeURIComponent(domain)}/reject`,
    rewardTopContributors: "/leaderboard/rewards/top-contributors",
  },
  risk: {
    me: "/risk/me",
    users: "/risk/users",
  },
  wallet: {
    me: "/wallet/me",
    transactions: "/wallet/transactions",
    transactionsExport: "/wallet/transactions/export",
    bootstrapInitial: "/wallet/bootstrap-initial",
  },
  seller: {
    dashboard: "/seller/dashboard",
    funnel: "/seller/funnel",
    couponPerformance: "/seller/coupon-performance",
    churnAlerts: "/seller/churn-alerts",
  },
  downloads: {
    note: (noteId) => `/download/${noteId}`,
  },
});
